import {
  Vendor,
  Product,
  Order,
  Category,
  AdminStats,
  VendorStats,
} from '@/types';

export const MOCK_VENDORS: Vendor[] = [
  {
    id: 'vendor-1',
    businessName: 'Kartong Fresh Farms',
    slug: 'kartong-fresh-farms',
    description:
      'Organic produce grown along the Kartong riverbanks in the South Bank.',
    logo: 'https://images.unsplash.com/photo-1560493676-04071c5f467b?w=80&h=80&fit=crop',
    banner:
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&h=200&fit=crop',
    ownerName: 'Lamin Ceesay',
    email: 'lamin@kartongfresh.gm',
    phone: '+2207201234',
    location: 'Kartong, South Bank',
    rating: 4.8,
    totalReviews: 134,
    isVerified: true,
    status: 'approved',
    commissionRate: 0.08,
    subscriptionPlan: 'pro',
    totalProducts: 22,
    totalOrders: 298,
    totalRevenue: 185000,
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'vendor-2',
    businessName: 'Basse Agro Supplies',
    slug: 'basse-agro-supplies',
    description: 'Premium grains and groundnuts from the Upper River Region.',
    ownerName: 'Fatou Jallow',
    email: 'fatou@basseagro.gm',
    phone: '+2207312345',
    location: 'Basse, Upper River Region',
    rating: 4.5,
    totalReviews: 87,
    isVerified: true,
    status: 'approved',
    commissionRate: 0.1,
    subscriptionPlan: 'free',
    totalProducts: 14,
    totalOrders: 172,
    totalRevenue: 142000,
    createdAt: '2024-02-20T10:00:00Z',
  },
  {
    id: 'vendor-3',
    businessName: 'Farafenni Market Co.',
    slug: 'farafenni-market',
    description:
      'Fresh vegetables and fruits from the North Bank bordertown market.',
    ownerName: 'Ousman Bojang',
    email: 'ousman@farafennimarket.gm',
    phone: '+2207423456',
    location: 'Farafenni, North Bank',
    rating: 4.1,
    totalReviews: 48,
    isVerified: false,
    status: 'pending',
    commissionRate: 0.1,
    subscriptionPlan: 'free',
    totalProducts: 7,
    totalOrders: 39,
    totalRevenue: 28000,
    createdAt: '2024-08-10T10:00:00Z',
  },
  {
    id: 'vendor-4',
    businessName: 'Yundum Dairy & Livestock',
    slug: 'yundum-dairy',
    description:
      'Pure dairy and livestock products from Yundum peri-urban farms.',
    ownerName: 'Mariama Sanneh',
    email: 'mariama@yundumdairy.gm',
    phone: '+2207534567',
    location: 'Yundum, West Coast Region',
    rating: 4.9,
    totalReviews: 189,
    isVerified: true,
    status: 'approved',
    commissionRate: 0.06,
    subscriptionPlan: 'enterprise',
    totalProducts: 30,
    totalOrders: 510,
    totalRevenue: 420000,
    createdAt: '2023-11-05T10:00:00Z',
  },
  {
    id: 'vendor-5',
    businessName: 'Banjul Spice Traders',
    slug: 'banjul-spice-traders',
    description:
      'Authentic Gambian spices, dried fish, and seasonings from the capital.',
    ownerName: 'Modou Touray',
    email: 'modou@banjulspice.gm',
    phone: '+2207645678',
    location: 'Banjul',
    rating: 3.9,
    totalReviews: 25,
    isVerified: false,
    status: 'suspended',
    commissionRate: 0.12,
    subscriptionPlan: 'free',
    totalProducts: 10,
    totalOrders: 58,
    totalRevenue: 16500,
    createdAt: '2024-05-22T10:00:00Z',
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: 'Organic Bitter Tomatoes',
    slug: 'organic-bitter-tomatoes',
    description:
      'Fresh bitter tomatoes grown without pesticides along the riverbank.',
    category: 'Vegetables',
    subCategory: 'Nightshades',
    price: 45,
    discountPrice: 35,
    stock: 400,
    unit: 'kg',
    images: [
      'https://images.unsplash.com/photo-1546470427-e26264be0b0f?w=400&h=300&fit=crop',
    ],
    isOrganic: true,
    isFeatured: true,
    harvestDate: '2025-03-10',
    location: 'Kartong',
    vendorId: 'vendor-1',
    vendorName: 'Kartong Fresh Farms',
    rating: 4.7,
    totalReviews: 76,
    createdAt: '2025-03-01T10:00:00Z',
  },
  {
    id: 'prod-2',
    name: 'Groundnuts (Shelled)',
    slug: 'groundnuts-shelled',
    description:
      'Premium shelled groundnuts — the backbone of Gambian agriculture.',
    category: 'Grains & Nuts',
    price: 120,
    stock: 300,
    unit: 'kg',
    images: [
      'https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?w=400&h=300&fit=crop',
    ],
    isOrganic: false,
    isFeatured: true,
    location: 'Basse',
    vendorId: 'vendor-2',
    vendorName: 'Basse Agro Supplies',
    rating: 4.6,
    totalReviews: 52,
    createdAt: '2025-02-15T10:00:00Z',
  },
  {
    id: 'prod-3',
    name: 'Benachin Rice (Local)',
    slug: 'benachin-rice-local',
    description: 'Locally grown swamp rice ideal for benachin and domoda.',
    category: 'Grains & Nuts',
    price: 95,
    stock: 800,
    unit: 'kg',
    images: [
      'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&h=300&fit=crop',
    ],
    isOrganic: true,
    isFeatured: true,
    location: 'Farafenni',
    vendorId: 'vendor-3',
    vendorName: 'Farafenni Market Co.',
    rating: 4.8,
    totalReviews: 110,
    createdAt: '2025-01-20T10:00:00Z',
  },
  {
    id: 'prod-4',
    name: 'Fresh Cow Milk',
    slug: 'fresh-cow-milk',
    description: 'Pure unprocessed cow milk from free-range Fulani cattle.',
    category: 'Dairy & Livestock',
    price: 25,
    stock: 600,
    unit: 'litre',
    images: [
      'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400&h=300&fit=crop',
    ],
    isOrganic: true,
    isFeatured: false,
    location: 'Yundum',
    vendorId: 'vendor-4',
    vendorName: 'Yundum Dairy & Livestock',
    rating: 4.9,
    totalReviews: 189,
    createdAt: '2025-03-05T10:00:00Z',
  },
  {
    id: 'prod-5',
    name: 'Garden Eggs (African Eggplant)',
    slug: 'garden-eggs',
    description:
      'Fresh garden eggs harvested daily — a staple in Gambian cooking.',
    category: 'Vegetables',
    price: 20,
    stock: 250,
    unit: 'kg',
    images: [
      'https://images.unsplash.com/photo-1524179091875-bf99a9a6af57?w=400&h=300&fit=crop',
    ],
    isOrganic: false,
    isFeatured: false,
    location: 'Farafenni',
    vendorId: 'vendor-3',
    vendorName: 'Farafenni Market Co.',
    rating: 4.2,
    totalReviews: 28,
    createdAt: '2025-03-08T10:00:00Z',
  },
  {
    id: 'prod-6',
    name: 'Dried Bonga Fish',
    slug: 'dried-bonga-fish',
    description:
      'Sun-dried bonga fish — essential flavouring for plasas and soups.',
    category: 'Fish & Seafood',
    price: 80,
    stock: 150,
    unit: 'kg',
    images: [
      'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=400&h=300&fit=crop',
    ],
    isOrganic: false,
    isFeatured: true,
    location: 'Banjul',
    vendorId: 'vendor-5',
    vendorName: 'Banjul Spice Traders',
    rating: 4.4,
    totalReviews: 63,
    createdAt: '2025-02-28T10:00:00Z',
  },
  {
    id: 'prod-7',
    name: 'Okra (Fresh)',
    slug: 'okra-fresh',
    description:
      'Tender fresh okra picked at peak ripeness for soups and stews.',
    category: 'Vegetables',
    price: 18,
    stock: 180,
    unit: 'kg',
    images: [
      'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&h=300&fit=crop',
    ],
    isOrganic: true,
    isFeatured: false,
    location: 'Kartong',
    vendorId: 'vendor-1',
    vendorName: 'Kartong Fresh Farms',
    rating: 4.5,
    totalReviews: 41,
    createdAt: '2025-03-12T10:00:00Z',
  },
  {
    id: 'prod-8',
    name: 'Millet (Sorghum)',
    slug: 'millet-sorghum',
    description:
      'Whole grain sorghum millet for porridge, chere, and animal feed.',
    category: 'Grains & Nuts',
    price: 55,
    stock: 500,
    unit: 'kg',
    images: [
      'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=400&h=300&fit=crop',
    ],
    isOrganic: false,
    isFeatured: false,
    location: 'Basse',
    vendorId: 'vendor-2',
    vendorName: 'Basse Agro Supplies',
    rating: 4.3,
    totalReviews: 34,
    createdAt: '2025-02-10T10:00:00Z',
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ORD-001',
    customerId: 'cust-1',
    customerName: 'Ebrima Baldeh',
    vendorId: 'vendor-1',
    vendorName: 'Kartong Fresh Farms',
    items: [
      {
        productId: 'prod-1',
        productName: 'Organic Bitter Tomatoes',
        productImage: '',
        quantity: 10,
        price: 35,
        unit: 'kg',
      },
      {
        productId: 'prod-7',
        productName: 'Okra (Fresh)',
        productImage: '',
        quantity: 5,
        price: 18,
        unit: 'kg',
      },
    ],
    totalAmount: 440,
    commissionAmount: 35,
    vendorEarning: 405,
    paymentMethod: 'wave',
    paymentStatus: 'paid',
    orderStatus: 'delivered',
    shippingAddress: 'Serrekunda, Kanifing',
    createdAt: '2025-03-01T08:30:00Z',
  },
  {
    id: 'ORD-002',
    customerId: 'cust-2',
    customerName: 'Adama Camara',
    vendorId: 'vendor-2',
    vendorName: 'Basse Agro Supplies',
    items: [
      {
        productId: 'prod-2',
        productName: 'Groundnuts (Shelled)',
        productImage: '',
        quantity: 20,
        price: 120,
        unit: 'kg',
      },
    ],
    totalAmount: 2400,
    commissionAmount: 240,
    vendorEarning: 2160,
    paymentMethod: 'afrimoney',
    paymentStatus: 'paid',
    orderStatus: 'shipped',
    shippingAddress: 'Brikama, West Coast Region',
    createdAt: '2025-03-05T11:00:00Z',
  },
  {
    id: 'ORD-003',
    customerId: 'cust-3',
    customerName: 'Isatou Dibba',
    vendorId: 'vendor-4',
    vendorName: 'Yundum Dairy & Livestock',
    items: [
      {
        productId: 'prod-4',
        productName: 'Fresh Cow Milk',
        productImage: '',
        quantity: 10,
        price: 25,
        unit: 'litre',
      },
    ],
    totalAmount: 250,
    commissionAmount: 15,
    vendorEarning: 235,
    paymentMethod: 'cash',
    paymentStatus: 'pending',
    orderStatus: 'confirmed',
    shippingAddress: 'Tallinding, Kanifing',
    createdAt: '2025-03-10T09:00:00Z',
  },
  {
    id: 'ORD-004',
    customerId: 'cust-4',
    customerName: 'Binta Jobe',
    vendorId: 'vendor-1',
    vendorName: 'Kartong Fresh Farms',
    items: [
      {
        productId: 'prod-1',
        productName: 'Organic Bitter Tomatoes',
        productImage: '',
        quantity: 8,
        price: 35,
        unit: 'kg',
      },
    ],
    totalAmount: 280,
    commissionAmount: 22,
    vendorEarning: 258,
    paymentMethod: 'wave',
    paymentStatus: 'paid',
    orderStatus: 'processing',
    shippingAddress: 'Bakau, Kanifing',
    createdAt: '2025-03-11T14:00:00Z',
  },
  {
    id: 'ORD-005',
    customerId: 'cust-5',
    customerName: 'Yankuba Sonko',
    vendorId: 'vendor-3',
    vendorName: 'Farafenni Market Co.',
    items: [
      {
        productId: 'prod-5',
        productName: 'Garden Eggs',
        productImage: '',
        quantity: 6,
        price: 20,
        unit: 'kg',
      },
    ],
    totalAmount: 120,
    commissionAmount: 12,
    vendorEarning: 108,
    paymentMethod: 'afrimoney',
    paymentStatus: 'failed',
    orderStatus: 'cancelled',
    shippingAddress: 'Farafenni, North Bank',
    createdAt: '2025-03-09T16:30:00Z',
  },
  {
    id: 'ORD-006',
    customerId: 'cust-6',
    customerName: 'Salimatou Kouyateh',
    vendorId: 'vendor-5',
    vendorName: 'Banjul Spice Traders',
    items: [
      {
        productId: 'prod-6',
        productName: 'Dried Bonga Fish',
        productImage: '',
        quantity: 3,
        price: 80,
        unit: 'kg',
      },
    ],
    totalAmount: 240,
    commissionAmount: 29,
    vendorEarning: 211,
    paymentMethod: 'cash',
    paymentStatus: 'paid',
    orderStatus: 'delivered',
    shippingAddress: 'Churchill Town, Banjul',
    createdAt: '2025-03-07T10:15:00Z',
  },
];

export const MOCK_CATEGORIES: import('@/types').Category[] = [
  {
    id: 'cat-1',
    name: 'Vegetables',
    slug: 'vegetables',
    icon: '🥬',
    productCount: 38,
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'cat-2',
    name: 'Fruits',
    slug: 'fruits',
    icon: '🍋',
    productCount: 24,
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'cat-3',
    name: 'Grains & Nuts',
    slug: 'grains-nuts',
    icon: '🌾',
    productCount: 31,
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'cat-4',
    name: 'Dairy & Livestock',
    slug: 'dairy-livestock',
    icon: '🥛',
    productCount: 16,
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'cat-5',
    name: 'Fish & Seafood',
    slug: 'fish-seafood',
    icon: '🐟',
    productCount: 22,
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'cat-6',
    name: 'Spices & Herbs',
    slug: 'spices-herbs',
    icon: '🌶️',
    productCount: 19,
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'cat-7',
    name: 'Poultry & Eggs',
    slug: 'poultry-eggs',
    icon: '🥚',
    productCount: 11,
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'cat-8',
    name: 'Root Crops',
    slug: 'root-crops',
    icon: '🍠',
    productCount: 14,
    createdAt: '2024-01-01T00:00:00Z',
  },
];

export const MOCK_ADMIN_STATS: AdminStats = {
  totalVendors: 5,
  totalProducts: 90,
  totalOrders: 1150,
  platformRevenue: 76400, // GMD
  pendingVendors: 1,
  monthlyRevenue: [
    { month: 'Oct', revenue: 48000 },
    { month: 'Nov', revenue: 55000 },
    { month: 'Dec', revenue: 69000 },
    { month: 'Jan', revenue: 58000 },
    { month: 'Feb', revenue: 64000 },
    { month: 'Mar', revenue: 76400 },
  ],
  recentOrders: MOCK_ORDERS.slice(0, 5),
};

export const MOCK_VENDOR_STATS: VendorStats = {
  totalProducts: 22,
  totalOrders: 298,
  totalRevenue: 185000, // GMD
  pendingOrders: 6,
  monthlyRevenue: [
    { month: 'Oct', revenue: 24000 },
    { month: 'Nov', revenue: 31000 },
    { month: 'Dec', revenue: 40000 },
    { month: 'Jan', revenue: 28000 },
    { month: 'Feb', revenue: 35000 },
    { month: 'Mar', revenue: 27000 },
  ],
  monthlyOrders: [
    { month: 'Oct', orders: 38 },
    { month: 'Nov', orders: 51 },
    { month: 'Dec', orders: 64 },
    { month: 'Jan', orders: 42 },
    { month: 'Feb', orders: 57 },
    { month: 'Mar', orders: 46 },
  ],
};
