import { Vendor, Product, Order, Category, AdminStats, VendorStats } from '@/types';

export const MOCK_VENDORS: Vendor[] = [
  {
    id: 'vendor-1',
    businessName: 'Green Valley Farms',
    slug: 'green-valley-farms',
    description: 'Organic produce from the heart of the valley.',
    logo: 'https://images.unsplash.com/photo-1560493676-04071c5f467b?w=80&h=80&fit=crop',
    banner: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&h=200&fit=crop',
    ownerName: 'James Mwangi',
    email: 'james@greenvalley.com',
    phone: '+254712345678',
    location: 'Nakuru, Kenya',
    rating: 4.8,
    totalReviews: 142,
    isVerified: true,
    status: 'approved',
    commissionRate: 0.08,
    subscriptionPlan: 'pro',
    totalProducts: 24,
    totalOrders: 312,
    totalRevenue: 2450000,
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'vendor-2',
    businessName: 'Sunrise Agro Supplies',
    slug: 'sunrise-agro',
    description: 'Premium grains and cereals from Eastern Kenya.',
    ownerName: 'Amina Hassan',
    email: 'amina@sunrise.co.ke',
    phone: '+254723456789',
    location: 'Meru, Kenya',
    rating: 4.5,
    totalReviews: 98,
    isVerified: true,
    status: 'approved',
    commissionRate: 0.10,
    subscriptionPlan: 'free',
    totalProducts: 15,
    totalOrders: 187,
    totalRevenue: 1820000,
    createdAt: '2024-02-20T10:00:00Z',
  },
  {
    id: 'vendor-3',
    businessName: 'Savanna Fresh Co.',
    slug: 'savanna-fresh',
    description: 'Fresh vegetables and fruits delivered daily.',
    ownerName: 'Peter Odhiambo',
    email: 'peter@savannafresh.co.ke',
    phone: '+254734567890',
    location: 'Kisumu, Kenya',
    rating: 4.2,
    totalReviews: 56,
    isVerified: false,
    status: 'pending',
    commissionRate: 0.10,
    subscriptionPlan: 'free',
    totalProducts: 8,
    totalOrders: 43,
    totalRevenue: 380000,
    createdAt: '2024-08-10T10:00:00Z',
  },
  {
    id: 'vendor-4',
    businessName: 'Highland Dairy Farm',
    slug: 'highland-dairy',
    description: 'Pure dairy products from highland cattle.',
    ownerName: 'Grace Njoroge',
    email: 'grace@highlanddairy.co.ke',
    phone: '+254745678901',
    location: 'Nyeri, Kenya',
    rating: 4.9,
    totalReviews: 203,
    isVerified: true,
    status: 'approved',
    commissionRate: 0.06,
    subscriptionPlan: 'enterprise',
    totalProducts: 32,
    totalOrders: 541,
    totalRevenue: 5200000,
    createdAt: '2023-11-05T10:00:00Z',
  },
  {
    id: 'vendor-5',
    businessName: 'Coast Spice Merchants',
    slug: 'coast-spice',
    description: 'Authentic coastal spices and seasonings.',
    ownerName: 'Ali Suleiman',
    email: 'ali@coastspice.co.ke',
    phone: '+254756789012',
    location: 'Mombasa, Kenya',
    rating: 3.8,
    totalReviews: 29,
    isVerified: false,
    status: 'suspended',
    commissionRate: 0.12,
    subscriptionPlan: 'free',
    totalProducts: 11,
    totalOrders: 67,
    totalRevenue: 210000,
    createdAt: '2024-05-22T10:00:00Z',
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: 'Organic Tomatoes',
    slug: 'organic-tomatoes',
    description: 'Fresh organic tomatoes grown without pesticides.',
    category: 'Vegetables',
    subCategory: 'Nightshades',
    price: 120,
    discountPrice: 95,
    stock: 500,
    unit: 'kg',
    images: ['https://images.unsplash.com/photo-1546470427-e26264be0b0f?w=400&h=300&fit=crop'],
    isOrganic: true,
    isFeatured: true,
    harvestDate: '2025-03-10',
    location: 'Nakuru',
    vendorId: 'vendor-1',
    vendorName: 'Green Valley Farms',
    rating: 4.7,
    totalReviews: 89,
    createdAt: '2025-03-01T10:00:00Z',
  },
  {
    id: 'prod-2',
    name: 'Maize (White)',
    slug: 'maize-white',
    description: 'Premium white maize from Eastern Kenya.',
    category: 'Grains',
    price: 4500,
    stock: 200,
    unit: 'bag',
    images: ['https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?w=400&h=300&fit=crop'],
    isOrganic: false,
    isFeatured: false,
    location: 'Meru',
    vendorId: 'vendor-2',
    vendorName: 'Sunrise Agro Supplies',
    rating: 4.5,
    totalReviews: 42,
    createdAt: '2025-02-15T10:00:00Z',
  },
  {
    id: 'prod-3',
    name: 'Avocados (Hass)',
    slug: 'avocados-hass',
    description: 'Premium Hass avocados, export quality.',
    category: 'Fruits',
    price: 85,
    stock: 1200,
    unit: 'piece',
    images: ['https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=400&h=300&fit=crop'],
    isOrganic: true,
    isFeatured: true,
    location: 'Muranga',
    vendorId: 'vendor-1',
    vendorName: 'Green Valley Farms',
    rating: 4.9,
    totalReviews: 156,
    createdAt: '2025-01-20T10:00:00Z',
  },
  {
    id: 'prod-4',
    name: 'Fresh Milk',
    slug: 'fresh-milk',
    description: 'Pure pasteurized milk from highland cows.',
    category: 'Dairy',
    price: 65,
    stock: 800,
    unit: 'kg',
    images: ['https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400&h=300&fit=crop'],
    isOrganic: true,
    isFeatured: false,
    location: 'Nyeri',
    vendorId: 'vendor-4',
    vendorName: 'Highland Dairy Farm',
    rating: 4.9,
    totalReviews: 203,
    createdAt: '2025-03-05T10:00:00Z',
  },
  {
    id: 'prod-5',
    name: 'Kale (Sukuma Wiki)',
    slug: 'kale-sukuma',
    description: 'Fresh kale harvested daily.',
    category: 'Vegetables',
    price: 30,
    stock: 300,
    unit: 'kg',
    images: ['https://images.unsplash.com/photo-1524179091875-bf99a9a6af57?w=400&h=300&fit=crop'],
    isOrganic: false,
    isFeatured: false,
    location: 'Kisumu',
    vendorId: 'vendor-3',
    vendorName: 'Savanna Fresh Co.',
    rating: 4.2,
    totalReviews: 31,
    createdAt: '2025-03-08T10:00:00Z',
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ORD-001',
    customerId: 'cust-1',
    customerName: 'John Kamau',
    vendorId: 'vendor-1',
    vendorName: 'Green Valley Farms',
    items: [
      { productId: 'prod-1', productName: 'Organic Tomatoes', productImage: '', quantity: 10, price: 95, unit: 'kg' },
      { productId: 'prod-3', productName: 'Avocados (Hass)', productImage: '', quantity: 20, price: 85, unit: 'piece' },
    ],
    totalAmount: 2650,
    commissionAmount: 212,
    vendorEarning: 2438,
    paymentStatus: 'paid',
    orderStatus: 'delivered',
    shippingAddress: 'Westlands, Nairobi',
    createdAt: '2025-03-01T08:30:00Z',
  },
  {
    id: 'ORD-002',
    customerId: 'cust-2',
    customerName: 'Mary Wanjiru',
    vendorId: 'vendor-2',
    vendorName: 'Sunrise Agro Supplies',
    items: [
      { productId: 'prod-2', productName: 'Maize (White)', productImage: '', quantity: 5, price: 4500, unit: 'bag' },
    ],
    totalAmount: 22500,
    commissionAmount: 2250,
    vendorEarning: 20250,
    paymentStatus: 'paid',
    orderStatus: 'shipped',
    shippingAddress: 'Thika, Kenya',
    createdAt: '2025-03-05T11:00:00Z',
  },
  {
    id: 'ORD-003',
    customerId: 'cust-3',
    customerName: 'David Ochieng',
    vendorId: 'vendor-4',
    vendorName: 'Highland Dairy Farm',
    items: [
      { productId: 'prod-4', productName: 'Fresh Milk', productImage: '', quantity: 20, price: 65, unit: 'kg' },
    ],
    totalAmount: 1300,
    commissionAmount: 78,
    vendorEarning: 1222,
    paymentStatus: 'pending',
    orderStatus: 'confirmed',
    shippingAddress: 'Ruiru, Kenya',
    createdAt: '2025-03-10T09:00:00Z',
  },
  {
    id: 'ORD-004',
    customerId: 'cust-4',
    customerName: 'Sarah Njoki',
    vendorId: 'vendor-1',
    vendorName: 'Green Valley Farms',
    items: [
      { productId: 'prod-1', productName: 'Organic Tomatoes', productImage: '', quantity: 5, price: 95, unit: 'kg' },
    ],
    totalAmount: 475,
    commissionAmount: 38,
    vendorEarning: 437,
    paymentStatus: 'paid',
    orderStatus: 'processing',
    shippingAddress: 'Karen, Nairobi',
    createdAt: '2025-03-11T14:00:00Z',
  },
  {
    id: 'ORD-005',
    customerId: 'cust-5',
    customerName: 'Alex Mutua',
    vendorId: 'vendor-3',
    vendorName: 'Savanna Fresh Co.',
    items: [
      { productId: 'prod-5', productName: 'Kale (Sukuma Wiki)', productImage: '', quantity: 8, price: 30, unit: 'kg' },
    ],
    totalAmount: 240,
    commissionAmount: 24,
    vendorEarning: 216,
    paymentStatus: 'failed',
    orderStatus: 'cancelled',
    shippingAddress: 'Kisumu CBD',
    createdAt: '2025-03-09T16:30:00Z',
  },
];

export const MOCK_CATEGORIES: import('@/types').Category[] = [
  { id: 'cat-1', name: 'Vegetables', slug: 'vegetables', icon: '🥬', productCount: 45, createdAt: '2024-01-01T00:00:00Z' },
  { id: 'cat-2', name: 'Fruits', slug: 'fruits', icon: '🍎', productCount: 32, createdAt: '2024-01-01T00:00:00Z' },
  { id: 'cat-3', name: 'Grains', slug: 'grains', icon: '🌾', productCount: 28, createdAt: '2024-01-01T00:00:00Z' },
  { id: 'cat-4', name: 'Dairy', slug: 'dairy', icon: '🥛', productCount: 19, createdAt: '2024-01-01T00:00:00Z' },
  { id: 'cat-5', name: 'Poultry', slug: 'poultry', icon: '🐓', productCount: 12, createdAt: '2024-01-01T00:00:00Z' },
  { id: 'cat-6', name: 'Spices', slug: 'spices', icon: '🌶️', productCount: 24, createdAt: '2024-01-01T00:00:00Z' },
];

export const MOCK_ADMIN_STATS: AdminStats = {
  totalVendors: 5,
  totalProducts: 90,
  totalOrders: 1150,
  platformRevenue: 984000,
  pendingVendors: 1,
  monthlyRevenue: [
    { month: 'Oct', revenue: 620000 },
    { month: 'Nov', revenue: 710000 },
    { month: 'Dec', revenue: 890000 },
    { month: 'Jan', revenue: 750000 },
    { month: 'Feb', revenue: 830000 },
    { month: 'Mar', revenue: 984000 },
  ],
  recentOrders: MOCK_ORDERS.slice(0, 5),
};

export const MOCK_VENDOR_STATS: VendorStats = {
  totalProducts: 24,
  totalOrders: 312,
  totalRevenue: 2450000,
  pendingOrders: 8,
  monthlyRevenue: [
    { month: 'Oct', revenue: 320000 },
    { month: 'Nov', revenue: 410000 },
    { month: 'Dec', revenue: 520000 },
    { month: 'Jan', revenue: 380000 },
    { month: 'Feb', revenue: 450000 },
    { month: 'Mar', revenue: 370000 },
  ],
  monthlyOrders: [
    { month: 'Oct', orders: 42 },
    { month: 'Nov', orders: 56 },
    { month: 'Dec', orders: 71 },
    { month: 'Jan', orders: 48 },
    { month: 'Feb', orders: 62 },
    { month: 'Mar', orders: 33 },
  ],
};
